image: ruby:2.3

before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
  - curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh" -o dropbox_uploader.sh
  - chmod +x dropbox_uploader.sh
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --gemfile falcon_factory_gem/Gemfile --jobs $(nproc)  "${FLAGS[@]}"

rspec:
  stage: test
  script:
    - rspec

rake:
 stage: deploy
 script:
  - cd falcon_factory_gem
  - rake build
  - ./dropbox_uploader.sh upload pkg/falcon_factory-0.0.1.gem  https://www.dropbox.com/sh/dizuwz5b7r8n1z9/AAABWT5uO2jkuTdJLXbKBKaWa?dl=0