#!/usr/bin/env ruby

require 'falcon_factory'
require 'optparse'



options = {}

opt_parser = OptionParser.new do |opt|
  opt.banner = "Usage: falcon_factory COMMAND [OPTIONS]"
  opt.separator  ""
  opt.separator "--------------------------------------------"
  opt.separator  "Commands"
  opt.separator  "    generate: Generate the application through a model"
  opt.separator "--------------------------------------------"
  opt.separator "--------------------------------------------"
  opt.separator  "Options"
  opt.on("-m","--model MODEL","Tell the folder path of your .yml database model") do
    |model|
      options[:model] = model
    end
  opt.on("-t","--target TARGET","Tell the folder path to store your generated application") do
  |target|
    options[:target] = target
  end

  opt.on("-h","--help","help") do
    puts opt_parser
  end

end

opt_parser.parse!
target = options[:target] || nil
model = options[:model] || nil

case ARGV[0]
when "generate"
  if model != ""
    puts "--------------------------------------------"
    puts "Attention: Model path not specified"
    puts "--------------------------------------------"
    puts opt_parser
  elsif target != ""
    puts "--------------------------------------------"
    puts "Attention: Target not specified"
    puts "--------------------------------------------"
    puts opt_parser
  else
  puts "model #{model}"
    puts "target #{target}"
    falcon = FalconFactory::FalconMain.new
    falcon.its_ok
  end
end
